Repository NUTFes/nutfes-Bingo, pull requests merged in 2023-11, with the labels that each got.

#151 Update issue-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: bug

#153 [fix] compress-ogp-image (#152)
  view-user/public/opengraph-image.png
Labels: bug, frontend

#155 Feat/yama/154 add multilingual support
  view-user/next.config.js
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/Modal/Modal.module.css
  view-user/src/components/common/Modal/Modal.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/pages/index.tsx
  view-user/src/pages/locales/en.ts
  view-user/src/pages/locales/ja.ts
  view-user/src/pages/prizes/index.tsx
  view-user/src/styles/Home.module.css
Labels: frontend

#157 景品ページに言語切り替えボタンを追加
  view-user/src/pages/prizes/index.tsx
  view-user/src/pages/prizes/prizes.module.css
Labels: frontend
