Repository NUTFes/nutfes-Bingo, pull requests merged in 2023-09, with the labels that each got.

#92 Feature/issue57/api image base64
  view-admin/src/pages/index.tsx
  view-admin/src/pages/testimage/index.tsx
  view-admin/src/styles/Home.module.css
  view-admin/src/utils/api_methods.ts
  view-user/src/utils/api_methods.ts
Labels: enhancement, frontend

#94 Fix/issue78/delete user pagestest
  view-admin/src/pages/test-keycloak.tsx
  view-user/src/components/common/TestBingoCreate/TestBingoCreate.tsx
  view-user/src/components/common/TestBingoCreate/index.ts
  view-user/src/components/common/TestBingoDelete/TestBingoDelete.tsx
  view-user/src/components/common/TestBingoDelete/index.ts
  view-user/src/components/common/TestBingoList/TestBingoList.tsx
  view-user/src/components/common/TestBingoList/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: bug, frontend

#88 [fix] 縁取りCSSを修正
  view-user/src/components/common/BingoResult/BingoResult.module.css
Labels: bug, frontend

#89 Fix/issue86/fix button
  view-admin/src/components/common/Button/Button.module.css
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#93 Feature/issue85/bingo number validation
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
Labels: enhancement, frontend

#96 Fix/issue95/prize page api
  view-admin/src/components/common/Header/Header.module.css
  view-admin/src/components/common/PrizeResult/PrizeResult.module.css
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/components/common/PrizeResult/index.ts
  view-admin/src/components/common/index.ts
  view-admin/src/pages/index.tsx
  view-admin/src/pages/prize-management.tsx
  view-admin/src/pages/prizes/index.tsx
  view-admin/src/pages/prizes/prizes.module.css
  view-admin/src/pages/testimage/index.tsx
  view-admin/src/utils/api_methods.ts
  view-user/src/components/common/PrizeResult/PrizeResult.module.css
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/PrizeResult/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/index.tsx
  view-user/src/pages/prize.tsx
  view-user/src/pages/prizes/index.tsx
  view-user/src/pages/prizes/prizes.module.css
  view-user/src/styles/prize.module.css
  view-user/src/utils/api_methods.ts
Labels: bug, frontend

#99 [fix] コードの修正
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/pages/index.tsx
  view-admin/src/pages/prizes/index.tsx
Labels: bug, frontend

#105 [add] 正誤判定モーダルのレスポンシブ対応
  view-admin/src/components/common/JudgementModal/JudgementModal.module.css
Labels: bug, frontend

#106 [fix] オーバーレイの不具合を修正
  view-admin/src/components/common/PrizeResult/PrizeResult.module.css
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.module.css
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
Labels: bug, frontend

#91 Feature/issue90/hasura admin secret
  docker-compose.yml
  view-admin/next.config.js
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/utils/api_methods.ts
  view-user/next.config.js
  view-user/package-lock.json
  view-user/package.json
  view-user/src/utils/api_methods.ts
Labels: enhancement, frontend, infra

#109 抽選順、昇順でビンゴ番号を表示できるようにした
  view-user/src/components/common/BingoResult/BingoResult.module.css
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/Button/Button.module.css
  view-user/src/components/common/Button/Button.types.ts
Labels: bug, frontend

#114 [mod] loadingがを画像が読み込み終わった後に非表示にするように修正
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
Labels: bug, frontend

#115 Fix/issue104/resposive admin page header
  view-admin/src/components/common/Button/Button.module.css
  view-admin/src/components/common/Header/Header.module.css
  view-admin/src/pages/index.tsx
  view-admin/src/pages/prizes/prizes.module.css
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#111 [mod] 正誤判定ボタンを押したときにテキストが出力されるように修正
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
Labels: bug, frontend

#122 [fix] 0が含まれる条件を考慮するように修正
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
Labels: bug, frontend

#120 Fix/issue119/del testimage fix prizename
  view-admin/src/pages/index.tsx
  view-admin/src/pages/prizes/index.tsx
  view-admin/src/pages/testimage/index.tsx
Labels: bug, frontend

#123 デプロイ(画像通信http化、ビンゴ正誤判定の修正、ヘッダーのレスポンシブ対応)
  view-admin/src/components/common/Header/Header.module.css
  view-admin/src/components/common/Header/Header.tsx
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/pages/index.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-admin/src/pages/prizes/index.tsx
  view-admin/src/pages/testimage/index.tsx
  view-admin/src/utils/api_methods.ts
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/Header/Header.tsx
  view-user/src/pages/prizes/index.tsx
  view-user/src/utils/api_methods.ts
Labels: frontend

#131 [fix] height→min-height
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#125 [mod] ページ遷移をuseRouterに変更
  view-admin/src/pages/index.tsx
Labels: bug, frontend

#135 Fix/issue134/fix admin overlay
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/components/common/PrizeResult/PrizeResult.module.css
  view-admin/src/pages/index.tsx
Labels: bug, frontend

#139 デプロイ
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/components/common/PrizeResult/PrizeResult.module.css
  view-admin/src/pages/index.tsx
Labels: frontend

#141 [fix] prizeのuseEffectをgetとsubscriptionに分けた
  view-admin/src/pages/prizes/index.tsx
  view-user/src/pages/prizes/index.tsx
Labels: bug, frontend

#142 デプロイ
  view-admin/src/pages/prizes/index.tsx
  view-user/src/pages/prizes/index.tsx
Labels: frontend
