Repository NUTFes/nutfes-Bingo, pull requests merged in 2023-07, with the labels that each got.

#10 Feature/issue7/edit templete
  .github/bingo-issue-templete.md
  .github/pull_request_template.md
  .github/workflows/auto-change-pr.yml
  .github/workflows/auto-prettier.yml
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement

#15 [add] Dev/issue12/create db
  .docker/api.Dockerfile
  Makefile
  api/config.yaml
  api/metadata/actions.graphql
  api/metadata/actions.yaml
  api/metadata/allow_list.yaml
  api/metadata/api_limits.yaml
  api/metadata/backend_configs.yaml
  api/metadata/cron_triggers.yaml
  api/metadata/databases/databases.yaml
  api/metadata/databases/default/tables/public_bingo_number.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/metadata/graphql_schema_introspection.yaml
  api/metadata/inherited_roles.yaml
  api/metadata/metrics_config.yaml
  api/metadata/network.yaml
  api/metadata/opentelemetry.yaml
  api/metadata/query_collections.yaml
  api/metadata/remote_schemas.yaml
  api/metadata/rest_endpoints.yaml
  api/metadata/version.yaml
  api/migrations/default/1688553000988_auto/up.sql
  api/migrations/default/1688553193922_auto/up.sql
  api/migrations/default/1688553262433_auto/up.sql
  api/migrations/default/1688877254430_auto/up.sql
  docker-compose.yml
  hasura/config.yml
Labels: backend, infra

#11 [add] next環境構築admin
  .docker/view-admin.Dockerfile
  README.md
  docker-compose.yml
  view-admin/.eslintrc.json
  view-admin/.gitignore
  view-admin/README.md
  view-admin/next.config.js
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/public/favicon.ico
  view-admin/public/next.svg
  view-admin/public/vercel.svg
  view-admin/src/pages/_app.tsx
  view-admin/src/pages/_document.tsx
  view-admin/src/pages/api/hello.ts
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
  view-admin/src/styles/globals.css
  view-admin/tsconfig.json
Labels: enhancement, frontend, infra

#21 [add] Create a modal to display results
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/Modal/Modal.module.css
  view-user/src/components/common/Modal/Modal.tsx
  view-user/src/components/common/Modal/index.ts
  view-user/src/components/common/index.ts
  view-user/src/styles/Home.module.css
Labels: enhancement, frontend

#23 [add]抽選済み番号一覧コンポーネントの作成
  view-user/src/components/common/BingoResult/BingoResult.module.css
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/BingoResult/index.ts
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/index.ts
  view-user/src/pages/index.tsx
  view-user/src/styles/Home.module.css
  view-user/src/styles/globals.css
Labels: enhancement, frontend
