Repository NUTFes/nutfes-Bingo, pull requests merged in 2023-08, with the labels that each got.

#30 Fix/issue29/fix modal compornent
  view-admin/package-lock.json
  view-admin/package.json
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/common/BingoResult/BingoResult.module.css
  view-user/src/components/common/Button/Button.module.css
  view-user/src/components/common/Button/Button.tsx
  view-user/src/components/common/Button/Button.types.ts
  view-user/src/components/common/Button/index.tsx
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/Modal/Modal.module.css
  view-user/src/components/common/Modal/Modal.tsx
  view-user/src/components/common/index.ts
  view-user/src/pages/index.tsx
  view-user/src/styles/Home.module.css
Labels: bug, frontend, infra

#33 [mod] 重複してimportを設定していたため修正
  view-user/src/components/common/index.ts
Labels: bug, frontend

#41 Feature/issue40/graph ql apimethods
  .gitignore
  docker-compose.yml
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/utils/api_methods.ts
  view-user/next.config.js
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/common/TestBingoCreate/TestBingoCreate.tsx
  view-user/src/components/common/TestBingoCreate/index.ts
  view-user/src/components/common/TestBingoDelete/TestBingoDelete.tsx
  view-user/src/components/common/TestBingoDelete/index.ts
  view-user/src/components/common/TestBingoList/TestBingoList.tsx
  view-user/src/components/common/TestBingoList/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
  view-user/src/utils/api_methods.ts
Labels: enhancement, frontend, infra

#44 Fix/issue38/fix user design
  view-user/src/components/common/BingoIcon/BingoIcon.tsx
  view-user/src/components/common/BingoIcon/index.ts
  view-user/src/components/common/BingoResult/BingoResult.module.css
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/index.ts
  view-user/src/pages/index.tsx
  view-user/src/styles/Home.module.css
Labels: bug, frontend

#47 Update pull_request_template.md
  .github/pull_request_template.md
Labels: bug

#46 Update issue templates
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: bug

#34 [add] 管理者ページの作成
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/components/common/BingoResult/BingoResult.module.css
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/components/common/BingoResult/index.ts
  view-admin/src/components/common/Button/Button.module.css
  view-admin/src/components/common/Button/Button.tsx
  view-admin/src/components/common/Button/Button.types.ts
  view-admin/src/components/common/Button/index.tsx
  view-admin/src/components/common/Header/Header.module.css
  view-admin/src/components/common/Header/Header.tsx
  view-admin/src/components/common/Header/index.ts
  view-admin/src/components/common/index.ts
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
Labels: enhancement, frontend

#50 issue43 WebSocket通信の実装
  view-user/next.config.js
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/common/TestBingoList/TestBingoList.tsx
  view-user/src/utils/api_methods.ts
Labels: enhancement, frontend

#49 Feature/issue48/api view user
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/pages/index.tsx
Labels: enhancement, frontend

#53 管理者ページのビンゴリストをDBから取得する&WebSocket通信
  docker-compose.yml
  view-admin/next.config.js
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/pages/index.tsx
  view-admin/src/utils/api_methods.ts
Labels: enhancement, frontend, infra

#55 userページの番号一覧をリアルタイム更新
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/pages/index.tsx
Labels: enhancement, frontend

#39 Feature/issue13/nose keycloak
  .gitignore
  docker-compose.yml
  view-admin/next.config.js
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/pages/_app.tsx
  view-admin/src/pages/api/auth/[...nextauth].ts
  view-admin/src/pages/index.tsx
  view-admin/src/pages/test-keycloak.tsx
Labels: enhancement, frontend, infra

#59 [mod] 重複していたenv_fileを削除
  docker-compose.yml
Labels: bug, infra

#45 cloudflare deploy setting
  .gitignore
  cloudflare/prod/config.yml
  docker-compose.prod.yml
Labels: enhancement, infra

#63 Fix/issue62/login design
  view-admin/package-lock.json
  view-admin/src/components/common/Button/Button.tsx
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#70 デプロイ更新
  .gitignore
  docker-compose.prod.yml
  docker-compose.yml
  view-admin/src/components/common/Button/Button.module.css
  view-admin/src/components/common/JudgementModal/JudgementModal.module.css
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/components/common/JudgementModal/index.ts
  view-admin/src/components/common/index.ts
  view-admin/src/pages/api/auth/[...nextauth].ts
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
Labels: frontend, infra

#74 [mod] デプロイ用makeの作成
  Makefile
Labels: enhancement

#71 [fix] 背景が画面いっぱいに描画されるように修正
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#72 [fix] フォントの縁取りCSSの変更
  view-user/src/components/common/BingoResult/BingoResult.module.css
  view-user/src/components/common/BingoResult/BingoResult.tsx
Labels: bug, frontend

#66 Fix/issue65/delete keycloak
  .docker/keycloak.Dockerfile
  .gitignore
  docker-compose.yml
Labels: bug, infra

#80 [mod] portの削除とenvファイルの指定
  docker-compose.prod.yml
Labels: bug, infra

#84 Feature/issue83/create admin prize list page
  view-admin/public/BingoCard.svg
  view-admin/public/GiftBox.svg
  view-admin/public/PrizeItem/01_Apple Watch SE.jpg
  view-admin/public/PrizeItem/02_黒毛和牛1kg.jpg
  view-admin/public/PrizeItem/03_選べるペアチケット.jpg
  view-admin/public/PrizeItem/04_コーヒーメーカー.jpg
  view-admin/public/PrizeItem/05_缶つま.jpg
  view-admin/public/PrizeItem/06_朝日山 天籟 越淡麗 純米大吟醸.jpg
  view-admin/public/PrizeItem/07_折りたたみ自転車.jpg
  view-admin/public/PrizeItem/08_焼肉プレート.jpg
  view-admin/public/PrizeItem/09_ジバニャン着ぐるみ.jpg
  view-admin/public/PrizeItem/10_チュッパチャプス200本ツリー.jpg
  view-admin/public/PrizeItem/11_技大セット.jpg
  view-admin/public/PrizeItem/12_瓶コーラ12本セット.jpg
  view-admin/public/PrizeItem/13_魚沼産コシヒカリ(2kg).jpg
  view-admin/public/PrizeItem/14_着る毛布(サメ).jpg
  view-admin/public/PrizeItem/15_駄菓子 詰め合わせセット.jpg
  view-admin/public/PrizeItem/16_トトロクッション.jpg
  view-admin/public/PrizeItem/17_ハンディファン.jpg
  view-admin/public/PrizeItem/18_サウナハット.jpg
  view-admin/public/PrizeItem/19_ご飯が炊ける弁当箱.jpg
  view-admin/public/PrizeItem/20_人生ゲームゴールデンドリーム.jpg
  view-admin/public/PrizeItem/21_寝袋.jpg
  view-admin/public/PrizeItem/22_ソーダストリーム.jpg
  view-admin/public/PrizeItem/23_ナブラ演算子ゲーム.jpg
  view-admin/public/PrizeItem/24_ダンベル.jpg
  view-admin/public/PrizeItem/25_ニュートンのゆりかご.jpg
  view-admin/public/PrizeItem/26_日めくりカレンダー(毎日アンミカ）.jpg
  view-admin/public/PrizeItem/27_セクシー大根抱き枕.jpg
  view-admin/public/PrizeItem/28_ペッパーミル.jpg
  view-admin/public/PrizeItem/29_ザコシショウ来学記念セット.jpg
  view-admin/public/PrizeItem/30_巨大クマのぬいぐるみ.jpg
  view-admin/public/PrizeItem/31_ハーゲンダッツ詰め合わせ.jpg
  view-admin/public/PrizeItem/シークレットアイコン.png
  view-admin/src/pages/index.tsx
  view-admin/src/pages/prize-management.tsx
  view-admin/src/styles/Home.module.css
  view-admin/src/styles/prize-management.module.css
Labels: enhancement, frontend

#56 Feature/issue51/create prize list page
  view-user/public/BingoCard.svg
  view-user/public/GiftBox.svg
  view-user/public/PrizeItem/01_Apple Watch SE.jpg
  view-user/public/PrizeItem/02_黒毛和牛1kg.jpg
  view-user/public/PrizeItem/03_選べるペアチケット.jpg
  view-user/public/PrizeItem/04_コーヒーメーカー.jpg
  view-user/public/PrizeItem/05_缶つま.jpg
  view-user/public/PrizeItem/06_朝日山 天籟 越淡麗 純米大吟醸.jpg
  view-user/public/PrizeItem/07_折りたたみ自転車.jpg
  view-user/public/PrizeItem/08_焼肉プレート.jpg
  view-user/public/PrizeItem/09_ジバニャン着ぐるみ.jpg
  view-user/public/PrizeItem/10_チュッパチャプス200本ツリー.jpg
  view-user/public/PrizeItem/11_技大セット.jpg
  view-user/public/PrizeItem/12_瓶コーラ12本セット.jpg
  view-user/public/PrizeItem/13_魚沼産コシヒカリ(2kg).jpg
  view-user/public/PrizeItem/14_着る毛布(サメ).jpg
  view-user/public/PrizeItem/15_駄菓子 詰め合わせセット.jpg
  view-user/public/PrizeItem/16_トトロクッション.jpg
  view-user/public/PrizeItem/17_ハンディファン.jpg
  view-user/public/PrizeItem/18_サウナハット.jpg
  view-user/public/PrizeItem/19_ご飯が炊ける弁当箱.jpg
  view-user/public/PrizeItem/20_人生ゲームゴールデンドリーム.jpg
  view-user/public/PrizeItem/21_寝袋.jpg
  view-user/public/PrizeItem/22_ソーダストリーム.jpg
  view-user/public/PrizeItem/23_ナブラ演算子ゲーム.jpg
  view-user/public/PrizeItem/24_ダンベル.jpg
  view-user/public/PrizeItem/25_ニュートンのゆりかご.jpg
  view-user/public/PrizeItem/26_日めくりカレンダー(毎日アンミカ）.jpg
  view-user/public/PrizeItem/27_セクシー大根抱き枕.jpg
  view-user/public/PrizeItem/28_ペッパーミル.jpg
  view-user/public/PrizeItem/29_ザコシショウ来学記念セット.jpg
  view-user/public/PrizeItem/30_巨大クマのぬいぐるみ.jpg
  view-user/public/PrizeItem/31_ハーゲンダッツ詰め合わせ.jpg
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/Button/Button.module.css
  view-user/src/components/common/Button/Button.tsx
  view-user/src/pages/index.tsx
  view-user/src/pages/prize.tsx
  view-user/src/styles/Home.module.css
  view-user/src/styles/prize.module.css
Labels: enhancement, frontend
