Repository NUTFes/nutfes-Bingo, pull requests merged in 2024-08, with the labels that each got.

#200 minIOの導入&dbのカラム名を修正
  .gitignore
  api/metadata/databases/default/tables/public_bingo_prize.yaml
  api/metadata/databases/default/tables/public_prize_image.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/migrations/default/1692550126540_auto/up.sql
  api/migrations/default/1720521696814_auto/up.sql
  docker-compose.yml
  view-admin/next.config.js
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/components/common/Loading/Loading.tsx
  view-admin/src/components/common/Loading/index.ts
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/components/common/index.ts
  view-admin/src/pages/_app.tsx
  view-admin/src/pages/api/minio.tsx
  view-admin/src/pages/api/schema.ts
  view-admin/src/pages/index.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-admin/src/pages/postPrizes/postPrizes.module.css
  view-admin/src/pages/prizes/index.tsx
  view-admin/src/type/common.ts
  view-user/next.config.js
  view-user/package-lock.json
  view-user/package.json
  view-user/src/Atom/atom.ts
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/pages/api/minio.tsx
  view-user/src/pages/api/schema.ts
  view-user/src/pages/index.tsx
  view-user/src/pages/prizes/index.tsx
  view-user/src/type/common.ts
Labels: enhancement, frontend, backend, infra

#213 NumberCardSmallコンポーネントの作成
  view-user/public/fonts/Silom.ttf
  view-user/src/components/common/NumberCardSmall/NumberCardSmall.module.css
  view-user/src/components/common/NumberCardSmall/NumberCardSmall.tsx
  view-user/src/components/common/NumberCardSmall/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/_app.tsx
  view-user/src/pages/test/index.tsx
  view-user/src/styles/globals.css
Labels: enhancement, frontend

#215 PrizeCardコンポーネントの実装
  view-user/src/components/common/PrizeCard/PrizeCard.module.css
  view-user/src/components/common/PrizeCard/PrizeCard.tsx
  view-user/src/components/common/PrizeCard/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#217 [fix]disabled属性の追加
  view-admin/src/pages/index.tsx
Labels: bug, frontend

#220 admin-secretを適用
  view-admin/next.config.js
  view-admin/src/pages/_app.tsx
  view-user/next.config.js
  view-user/src/pages/_app.tsx
Labels: bug, frontend

#221 リアクションスタンプモーダルの作成
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.module.css
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.tsx
  view-user/src/components/common/ReactionStampModal/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#224 ナンバーカードをまとめるコンポーネントの作成
  view-user/src/components/common/NumberCardList/NumberCardList.module.css
  view-user/src/components/common/NumberCardList/NumberCardList.tsx
  view-user/src/components/common/NumberCardList/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#211 枠組みのアイコンコンポーネントとPrizesアイコンの作成
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/common/IconFramework/IconFramework.module.css
  view-user/src/components/common/IconFramework/IconFramework.tsx
  view-user/src/components/common/IconFramework/index.ts
  view-user/src/components/common/PrizesIcon/PrizesIcon.module.tsx
  view-user/src/components/common/PrizesIcon/PrizesIcon.tsx
  view-user/src/components/common/PrizesIcon/index.ts
  view-user/src/components/common/index.ts
Labels: frontend

#229 [feat]ヘッダーコンポーネントの作成
  package-lock.json
  view-user/public/Bingo_logo.png
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/Header/Header.tsx
  view-user/src/pages/index.tsx
Labels: frontend

#222 [fix]送信ボタンの伸縮を無くす
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#235 PrizeCardListコンポーネントの作成
  view-user/src/components/common/PrizeCard/PrizeCard.module.css
  view-user/src/components/common/PrizeCard/PrizeCard.tsx
  view-user/src/components/common/PrizeCardList/PrizeCardList.module.css
  view-user/src/components/common/PrizeCardList/PrizeCardList.tsx
  view-user/src/components/common/PrizeCardList/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#232 リーチアイコンコンポーネントの作成
  view-user/public/reach-icon-inversion.svg
  view-user/public/reach-icon.svg
  view-user/src/components/common/ReachIcon/ReachIcon.module.css
  view-user/src/components/common/ReachIcon/ReachIcon.tsx
  view-user/src/components/common/ReachIcon/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#243 トグルボタンコンポーネントの作成
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/common/ToggleButton/ToggleButton.module.css
  view-user/src/components/common/ToggleButton/ToggleButton.tsx
  view-user/src/components/common/ToggleButton/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#248 NavigationBarとレイアウトの作成
  view-user/src/components/Layout/Layout.module.css
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/Layout/index.ts
  view-user/src/components/common/NavigationBar/NavigationBar.module.css
  view-user/src/components/common/NavigationBar/NavigationBar.tsx
  view-user/src/components/common/NavigationBar/index.ts
  view-user/src/components/common/ReachIcon/ReachIcon.tsx
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#246 [feat]Modal componentの作成
  view-user/src/components/common/Modal/Modal.module.css
  view-user/src/components/common/Modal/Modal.tsx
Labels: frontend

#242 [feat]ボタンコンポーネントの作成
  view-user/src/components/common/Button/Button.module.css
  view-user/src/components/common/Button/Button.tsx
  view-user/src/components/common/Button/Button.types.ts
  view-user/src/pages/test/index.tsx
  view-user/src/styles/Home.module.css
Labels: frontend

#240 バックアイコンの作成
  view-user/src/components/common/BackIcon/BackIcon.module.css
  view-user/src/components/common/BackIcon/BackIcon.tsx
  view-user/src/components/common/BackIcon/index.ts
  view-user/src/components/common/index.ts
Labels: frontend

#238 SettingIconコンポーネントの作成(onClickの処理は未実装)
  view-user/src/components/common/SettingsIcon/SettingIcon.module.css
  view-user/src/components/common/SettingsIcon/SettingIcon.tsx
  view-user/src/components/common/SettingsIcon/index.ts
  view-user/src/components/common/index.ts
Labels: frontend

#228 reactionsIconコンポーネントの作成
  view-user/src/components/common/IconFramework/IconFramework.tsx
  view-user/src/components/common/ReactionsIcon/ReactionsIcon.module.css
  view-user/src/components/common/ReactionsIcon/ReactionsIcon.tsx
  view-user/src/components/common/ReactionsIcon/index.ts
  view-user/src/components/common/index.ts
Labels: frontend

#218 抽選された番号を格納する大きいコンポーネントを作成しました。
  view-user/src/components/common/NumberCardLarge/NumberCardLarge.module.css
  view-user/src/components/common/NumberCardLarge/NumberCardLarge.tsx
  view-user/src/components/common/NumberCardLarge/index.ts
  view-user/src/components/common/index.ts
Labels: frontend

#254 NavigationBarの配置を正規のものにした＆リアクションモーダルの位置をnavbarの上に調整
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/NavigationBar/NavigationBar.tsx
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.module.css
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.tsx
  view-user/src/pages/test/index.tsx
Labels: frontend

#268 prize pageの作成
  view-user/src/components/common/Loading/Loading.module.css
  view-user/src/components/common/Loading/Loading.tsx
  view-user/src/components/common/PrizeCardList/PrizeCardList.module.css
  view-user/src/components/common/PrizeCardList/PrizeCardList.tsx
  view-user/src/pages/prizes/index.tsx
  view-user/src/pages/prizes/prizes.module.css
Labels: frontend

#274 headerを固定した
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/Layout/Layout.module.css
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/NavigationBar/NavigationBar.module.css
  view-user/src/pages/test/index.tsx
Labels: bug, frontend

#270 DBテーブル名・カラム名の修正 #227
  api/metadata/databases/databases.yaml
  api/metadata/databases/default/tables/public_images.yaml
  api/metadata/databases/default/tables/public_numbers.yaml
  api/metadata/databases/default/tables/public_prizes.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/migrations/default/1720521696814_auto/up.sql
  docker-compose.yml
  view-admin/codegen.ts
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/gql/images.gql
  view-admin/src/gql/numbers.gql
  view-admin/src/gql/prizes.gql
  view-admin/src/pages/api/schema.ts
  view-admin/src/pages/index.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-admin/src/pages/prizes/index.tsx
  view-admin/src/type/common.ts
  view-admin/src/type/graphql.ts
  view-user/codegen.ts
  view-user/package-lock.json
  view-user/package.json
  view-user/src/Atom/atom.ts
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/NumberCardList/NumberCardList.tsx
  view-user/src/components/common/NumberCardSmall/NumberCardSmall.tsx
  view-user/src/components/common/PrizeCard/PrizeCard.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/gql/images.gql
  view-user/src/gql/numbers.gql
  view-user/src/gql/prizes.gql
  view-user/src/pages/api/schema.ts
  view-user/src/pages/index.tsx
  view-user/src/pages/prizes/index.tsx
  view-user/src/type/common.ts
  view-user/src/type/graphql.ts
Labels: bug, frontend, backend, infra

#278 トップページの作成
  view-user/src/components/Layout/Layout.module.css
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/Loading/Loading.module.css
  view-user/src/components/common/Loading/Loading.tsx
  view-user/src/components/common/NavigationBar/NavigationBar.module.css
  view-user/src/components/common/NumberCardLarge/NumberCardLarge.tsx
  view-user/src/components/common/NumberCardList/NumberCardList.module.css
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.module.css
  view-user/src/components/common/SettingsIcon/SettingsIcon.tsx
  view-user/src/components/index.ts
  view-user/src/locales/index.ts
  view-user/src/pages/_app.tsx
  view-user/src/pages/index.tsx
  view-user/src/styles/Home.module.css
  view-user/src/styles/globals.css
Labels: frontend

#280 Settingsモーダルの作成＆多言語化対応
  view-user/src/components/Layout/Layout.module.css
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/IconFramework/IconFramework.tsx
  view-user/src/components/common/SettingsIcon/SettingsIcon.tsx
  view-user/src/components/common/ToggleButton/ToggleButton.tsx
  view-user/src/locales/en.ts
  view-user/src/locales/ja.ts
  view-user/src/pages/index.tsx
Labels: frontend

#285 lintの修正
  .github/workflows/auto-prettier-admin.yml
  .github/workflows/auto-prettier-user.yml
  view-admin/codegen.ts
  view-user/codegen.ts
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/BingoResult/BingoResult.module.css
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/BingoResult/index.ts
  view-user/src/components/common/PrizeCard/PrizeCard.tsx
  view-user/src/components/common/PrizeCardList/PrizeCardList.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/SettingsIcon/SettingsIcon.tsx
  view-user/src/components/common/index.ts
  view-user/src/pages/test/index.tsx
Labels: frontend

#283 Dockerファイルの修正
  .docker/api.Dockerfile
  docker-compose.prod.yml
  docker-compose.yml
Labels: infra

#286 minio再導入
  view-admin/package-lock.json
  view-admin/package.json
  view-user/package-lock.json
  view-user/package.json
Labels: bug, frontend

#284 リーチカウントのAPIを作成【view-user】
  api/metadata/databases/default/tables/public_reach_logs.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/migrations/default/1720521696814_auto/up.sql
  view-user/src/components/Layout/Layout.tsx
  view-user/src/gql/reach_logs.gql
  view-user/src/type/graphql.ts
Labels: frontend, backend

#282 正誤判定モーダルを刷新
  view-admin/src/components/common/JudgementModal/JudgementModal.module.css
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
Labels: frontend

#279 stampAPIの作成とscreenページの実装
  Makefile
  api/metadata/databases/default/tables/public_bingo_number.yaml
  api/metadata/databases/default/tables/public_bingo_prize.yaml
  api/metadata/databases/default/tables/public_stamp_triggers.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/migrations/default/1720521696814_auto/up.sql
  docker-compose.yml
  view-admin/src/type/graphql.ts
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/NumberCardLarge/NumberCardLarge.module.css
  view-user/src/components/common/NumberCardList/NumberCardList.module.css
  view-user/src/components/common/NumberCardList/NumberCardList.tsx
  view-user/src/components/common/NumberCardSmall/NumberCardSmall.module.css
  view-user/src/components/common/NumberCardSmall/NumberCardSmall.tsx
  view-user/src/components/common/ReachCount/styles.module.css
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.tsx
  view-user/src/components/common/SettingsIcon/SettingsIcon.tsx
  view-user/src/gql/numbers.gql
  view-user/src/gql/stamp_triggers.gql
  view-user/src/pages/ScreenPage/index.tsx
  view-user/src/pages/index.tsx
  view-user/src/pages/screen/index.tsx
  view-user/src/pages/screen/screen.module.css
  view-user/src/type/graphql.ts
Labels: frontend, backend, infra

#288 prizesぺージの修正
  view-user/next.config.js
  view-user/src/Atom/atom.ts
  view-user/src/components/common/Header/Header.module.css
  view-user/src/components/common/PrizeCard/PrizeCard.module.css
  view-user/src/components/common/PrizeCard/PrizeCard.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.module.css
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/PrizeResult/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/prizes/index.tsx
  view-user/src/pages/prizes/prizes.module.css
Labels: bug, frontend

#281 admin画面のデザイン変更
  view-admin/src/components/common/BingoResult/BingoResult.module.css
  view-admin/src/components/common/Button/Button.module.css
  view-admin/src/components/common/Header/Header.module.css
  view-admin/src/components/common/PrizeResult/PrizeResult.module.css
  view-admin/src/pages/postPrizes/postPrizes.module.css
  view-admin/src/pages/prizes/prizes.module.css
  view-admin/src/styles/Home.module.css
Labels: bug, frontend
