Repository NUTFes/nutfes-Bingo, pull requests merged in 2024-09, with the labels that each got.

#299 リアクションのアイコンを小さくする
  view-admin/package-lock.json
  view-admin/package.json
  view-user/package-lock.json
  view-user/package.json
  view-user/src/pages/screen/index.tsx
Labels: bug, frontend

#292 正誤判定のバグ修正
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
Labels: bug, frontend

#297 抽選番号の表示順をlocalstorageへ保存する機能を実装
  view-user/src/components/Layout/Layout.tsx
  view-user/src/pages/index.tsx
Labels: frontend

#300 fix keycloakの復活
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
Labels: bug, frontend

#308 スタンプにアニメーションを追加
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.module.css
Labels: bug, frontend

#295 景品のオーバーレイ修正＆フォントカラーの変更
  view-admin/next.config.js
  view-admin/src/components/common/PrizeResult/PrizeResult.module.css
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/PrizeCard/PrizeCard.module.css
  view-user/src/components/common/PrizeCard/PrizeCard.tsx
Labels: frontend

#305 reach増減APIの修正
  api/metadata/databases/databases.yaml
  api/metadata/databases/default/functions/functions.yaml
  api/metadata/databases/default/functions/public_decrement_latest_reach_log.yaml
  api/metadata/databases/default/functions/public_increment_latest_reach_log.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/migrations/default/1720521696814_auto/up.sql
  view-admin/src/gql/reach_log.gql
  view-admin/src/pages/index.tsx
  view-admin/src/type/graphql.ts
Labels: bug, frontend, backend

#306 stampAPIの改修
  api/migrations/default/1720521696814_auto/up.sql
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/ReactionStampModal/ReactionStampModal.tsx
  view-user/src/gql/stamp_triggers.gql
  view-user/src/pages/screen/index.tsx
  view-user/src/type/graphql.ts
Labels: bug, frontend, backend

#307 updataモーダルの作成
  view-admin/src/components/common/BingoResult/BingoResult.module.css
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/components/common/UpdateNumberModal/UpdateNumberModal.module.css
  view-admin/src/components/common/UpdateNumberModal/UpdateNumberModal.tsx
  view-admin/src/components/common/UpdateNumberModal/index.ts
  view-admin/src/components/common/index.ts
  view-admin/src/gql/numbers.gql
  view-admin/src/pages/index.tsx
  view-admin/src/type/graphql.ts
  view-user/src/pages/index.tsx
  view-user/src/pages/screen/index.tsx
Labels: bug, frontend, backend

#289 デプロイ時に出た修正をここにまとめる
  Makefile
  docker-compose.prod.yml
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/pages/api/minio.ts
  view-admin/src/pages/api/minio.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-user/src/pages/index.tsx
  view-user/src/pages/prizes/index.tsx
Labels: bug, frontend, infra

#309 Helpページの追加
  package-lock.json
  view-user/package-lock.json
  view-user/package.json
  view-user/public/Help_slide1.png
  view-user/public/Help_slide2.png
  view-user/public/Help_slide3.png
  view-user/public/Help_slide4.png
  view-user/public/Help_slide5.png
  view-user/src/components/common/DotButton/DotButton.module.css
  view-user/src/components/common/DotButton/DotButton.tsx
  view-user/src/components/common/DotButton/index.ts
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/HelpCarousel/HelpCarousel.module.css
  view-user/src/components/common/HelpCarousel/HelpCarousel.tsx
  view-user/src/components/common/HelpCarousel/index.ts
  view-user/src/components/common/index.ts
  view-user/src/locales/en.ts
  view-user/src/locales/ja.ts
Labels: frontend

#310 テストデプロイ時に出たエラー
  api/migrations/default/1720521696814_auto/up.sql
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/gql/reach_log.gql
  view-admin/src/type/graphql.ts
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/NumberCardLarge/NumberCardLarge.tsx
  view-user/src/gql/reach_logs.gql
  view-user/src/gql/stamp_triggers.gql
  view-user/src/pages/prizes/index.tsx
  view-user/src/pages/screen/index.tsx
  view-user/src/type/graphql.ts
Labels: bug, frontend, backend

#312 screenのcreatedAT取得を変更
  view-user/src/pages/screen/index.tsx
Labels: bug, frontend

#313 でプロい
  view-user/src/pages/screen/index.tsx
Labels: frontend
