Repository NUTFes/nutfes-Bingo, pull requests merged in 2024-04, with the labels that each got.

#170 Feat/yama/168 fix design post prizes
  view-admin/public/image-placeholder.png
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-admin/src/pages/postPrizes/postPrizes.module.css
Labels: frontend

#169 apolo/clientへの置き換え
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/components/common/JudgementModal/JudgementModal.tsx
  view-admin/src/components/common/PrizeResult/PrizeResult.tsx
  view-admin/src/pages/_app.tsx
  view-admin/src/pages/api/schema.ts
  view-admin/src/pages/index.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-admin/src/pages/prizes/index.tsx
  view-admin/src/utils/api_methods.ts
  view-user/package-lock.json
  view-user/package.json
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.module.css
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/pages/Atom/atom.ts
  view-user/src/pages/_app.tsx
  view-user/src/pages/api/schema.ts
  view-user/src/pages/index.tsx
  view-user/src/pages/prizes/index.tsx
  view-user/src/utils/api_methods.ts
Labels: bug, frontend, backend

#174 [fix] lintの修正
  view-admin/src/components/common/BingoResult/BingoResult.tsx
  view-admin/src/components/common/BingoResult/index.ts
  view-admin/src/components/common/Button/Button.tsx
  view-admin/src/components/common/Button/Button.types.ts
  view-admin/src/components/common/Button/index.tsx
  view-admin/src/components/common/Header/index.ts
  view-admin/src/components/common/JudgementModal/index.ts
  view-admin/src/components/common/PrizeResult/index.ts
  view-admin/src/components/common/index.ts
  view-admin/src/pages/_document.tsx
  view-admin/src/pages/api/auth/[...nextauth].ts
  view-admin/src/pages/api/hello.ts
  view-user/src/components/common/BingoIcon/index.ts
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/BingoResult/index.ts
  view-user/src/components/common/Button/Button.tsx
  view-user/src/components/common/Button/index.tsx
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/Header/index.ts
  view-user/src/components/common/Modal/Modal.tsx
  view-user/src/components/common/Modal/index.ts
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/components/common/PrizeResult/index.ts
  view-user/src/components/common/index.ts
  view-user/src/pages/_document.tsx
  view-user/src/pages/api/hello.ts
  view-user/src/pages/locales/en.ts
  view-user/src/pages/locales/ja.ts
Labels: bug, frontend

#177 pagesの外に置いてみた
  view-user/src/Atom/atom.ts
  view-user/src/components/common/BingoResult/BingoResult.tsx
  view-user/src/components/common/PrizeResult/PrizeResult.tsx
  view-user/src/locales/en.ts
  view-user/src/locales/ja.ts
  view-user/src/pages/index.tsx
  view-user/src/pages/prizes/index.tsx
Labels: bug, frontend
