Repository NUTFes/nutfes-Bingo, pull requests merged in 2025-08, with the labels that each got.

#337 toastメッセージの追加、英語の入力フォームの追加
  docker-compose.yml
  view-admin/package-lock.json
  view-admin/package.json
  view-admin/src/pages/_app.tsx
  view-admin/src/pages/postPrizes/index.tsx
  view-admin/src/pages/postPrizes/postPrizes.module.css
Labels: bug, frontend, infra

#345 管理者が手動でアンケートを流す機能の実装
  api/metadata/databases/default/tables/public_events.yaml
  api/metadata/databases/default/tables/tables.yaml
  api/migrations/default/1720521696814_auto/up.sql
  view-admin/src/gql/events.gql
  view-admin/src/pages/index.tsx
  view-admin/src/styles/Home.module.css
  view-admin/src/type/graphql.ts
  view-user/src/components/Layout/Layout.module.css
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/SurveyPromptModal/SurveyPromptModal.module.css
  view-user/src/components/common/SurveyPromptModal/SurveyPromptModal.tsx
  view-user/src/components/common/index.ts
  view-user/src/gql/events.gql
  view-user/src/hooks/useSurveyState.ts
  view-user/src/locales/en.ts
  view-user/src/locales/ja.ts
  view-user/src/state/survey.ts
  view-user/src/types/graphql.ts
Labels: frontend, backend

#350 [fix] 戻るボタンのテキストとアイコンの更新、ヘルプカルーセルの条件を修正
  view-user/src/components/Layout/Layout.tsx
  view-user/src/components/common/Header/Header.tsx
  view-user/src/components/common/icons/BackIcon/BackIcon.tsx
  view-user/src/locales/en.ts
  view-user/src/locales/ja.ts
Labels: bug, frontend

#330 numbersにuniqueを付与
  .vscode/settings.json
  api/migrations/default/1720521696814_auto/up.sql
  view-admin/src/pages/index.tsx
  view-user/package-lock.json
  view-user/package.json
Labels: bug, frontend, backend, infra
